### PR TITLE
ValidatorFieldsProof: support multiple validatorIndex

### PR DESCRIPTION
**Pull request by llifezou**
Support multiple validatorIndex for `-command ValidatorFieldsProof`

### CODE REVIEW

**Comment by llifezou** [comment]
for https://github.com/Layr-Labs/eigenpod-proofs-generation/issues/61

**Comment by llifezou** [comment]
@Sidu28 Hi, If this is of value I'll proceed with the other two commands. If not needed, I will close this PR

**Comment by Sidu28** [comment]
@llifezou can you rebase ur branch?  I can review it then

**Comment by llifezou** [comment]
> @llifezou can you rebase ur branch? I can review it then

@Sidu28  completed

**Pull request closed without merging**
